# Site
# repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Erik Bergstedt
title: Solution Architect
email: bergstedt.erik@gmail.com
website: https://github.com/ebergstedt

# Social links
# twitter_username: facespics
github_username: ebergstedt
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: erikbergstedt
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  As a solution architect, my strength lies in creative incentives both at the low level of implementation and high level of business operation - improving code stability and performance, making long-term cost-efficient architecture choices fitting your requirements and helping your other developers to make the best product they can.
  
  I have a wide breadth of knowledge, including but not limited to: .NET architecture, Azure cloud architecture, full-stack web development, API design and setup and implementaton of all stages of DevOps (coding, building tools, deployment and packaging, release automation, infrastructure configuration and monitoring).

# Projects Section
# projects_title: Projects

    test1

# Experience Section
# experience_title: Experience

    test2

# Education Section
# educaton_title: Education

    test3

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
