# Site
# repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Erik Bergstedt
title: Solutions Architect
email: bergstedt.erik@gmail.com
website: https://github.com/ebergstedt

# Social links
# twitter_username: businessbro7
github_username: ebergstedt
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: businessbro7
linkedin_username: erikbergstedt
# pinterest_username: jekyll
# youtube_username: channel/UCgB297rK0gFSIDTt4d9yN2Q
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  As a Solutions Architect I take responsibility to drive your company vision forward, with creative and valuable incentives in both business and implementation. I enjoy improving code stability and performance, with long-term cost-efficient architectural choices, but also teaching and enabling other developers to make the best product they can.

  I have 10 years of experience with a wide breadth of knowledge, including but not limited to: 
  * .NET architecture design
  * Distributed system design
  * Cloud architecture design (Azure, AWS, Google Cloud)
  * API design and implementation
  * Full-stack web development  
  * Big Data, database design and optimization (Relational, NoSQL, hybrid)  
  * Setup and implementaton of DevOps (coding, building tools, deployment and packaging, release automation, infrastructure configuration and monitoring)
  * Language skills include C#, Python, SQL, F#, Java, JavaScript, C, C++ and R
  
  Leveraging my quantitative finance knowledge, I also 2 years of non-professional experience with investing, with a focus on risk management. This has yielded between 10-15% MTD average gain. Details of portfolio performance may be given upon request.

 #As a <mark>Solutions Architect</mark> my strength lies in taking responsibility to drive your business forward with creative incentives at the levels of implementation and business operation - improving code stability and performance, with long-term cost-efficient architecture choices fitting your requirements and helping your other developers to make the best product they can.
  
 #I have a wide breadth of knowledge, including but not limited to: <mark>.NET Architecture</mark>, <mark>Azure Cloud Architecture</mark>, <mark>Full-stack Web Development</mark>, <mark>API Design</mark>, <mark>Big Data</mark>, setup and implementaton in all stages of <mark>DevOps</mark> (coding, building tools, deployment and packaging, release automation, infrastructure configuration and monitoring), <mark>Database Design and Optimization</mark>. Language skills include <mark>C#</mark>, <mark>SQL</mark>, <mark>F#</mark>, <mark>Java</mark>, <mark>JavaScript</mark>, <mark>Python</mark> and <mark>C and C++</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in programming some of my other interests and hobbies are:
   - Cooking and nutritional science
   - Physiology and psychology
   - Gaming
   - Weight lifting

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
